// <auto-generated />
using GetraenkeautomatVorrat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetraenkeautomatVorrat.Migrations
{
    [DbContext(typeof(VorratContext))]
    [Migration("20250716084913_table-2025-07-16_2")]
    partial class table20250716_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GetraenkeautomatVorrat.Vorrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Groesse")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preis")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Vorrat");
                });
#pragma warning restore 612, 618
        }
    }
}
